# Data Science Project 1: Data Wrangling Practical
**Duration:** 1 Hour, 15 Minutes  
**Format:** Open-notes code implementation (Python/Pandas)

### **Project Scenario**
You have been given a raw slice of **Glassdoor Data Science Job Postings**. The dataset contains a variety of small errors, missing variables, and split locations. Your goal is to clean this main dataset, create engineered features, and merge it with a regional mapping file so the analytics team can use it.

## Load the data
Download the data from the Blackboard to your computer frist, then load your libraries and the datasets required for this exam here.

In [6]:
# import all libaries and load your datasets your here
import pandas as pd
import numpy as np
jobs = pd.read_csv("glassdoor_jobs.csv")
state_regions = pd.read_csv("state_regions.csv")

## Part 1: Missing Data & Filtering (30 Points)

### **Task 1.1 (Standardizing Nulls)**
The `Rating` column represents missing values as `-1`. Replace all occurrences of `-1` with the dataset's overall **average (mean)** rating value.

In [15]:
# Write your solution for Task 1.1 here

jobs['Rating'] = jobs['Rating'].replace(-1, np.nan)

#Fill the missing values with the overall mean of the valid ratings
overall_mean = jobs['Rating'].mean()
jobs['Rating'] = jobs['Rating'].fillna(overall_mean)

jobs.head()

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY",1993,Insurance Carriers
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA",1968,Research & Development
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,2.984226,Analysis Group\n3.8,"Boston, MA",1981,Consulting
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA",2000,Electrical & Electronic Manufacturing
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY",1998,Advertising & Marketing

### **Task 1.2 (Handling Blanks)**
The `Industry` column has several completely blank or empty cells. Fill these missing values with the string text `"Unknown"`.

In [16]:
# Write your solution for Task 1.2 here
jobs['Industry'] = jobs['Industry'].replace('', 'Unknown')
jobs.head()

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY",1993,Insurance Carriers
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA",1968,Research & Development
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,2.984226,Analysis Group\n3.8,"Boston, MA",1981,Consulting
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA",2000,Electrical & Electronic Manufacturing
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY",1998,Advertising & Marketing

### **Task 1.3 (Data Filtering)**
A few rows contain placeholder or invalid values in the `Founded` year column (values less than or equal to `0`). **Filter the dataset** to permanently remove these invalid rows.

In [19]:
# Write your solution for Task 1.3 here
jobs = jobs[jobs['Founded'] > 0]
jobs.head()

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY",1993,Insurance Carriers
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA",1968,Research & Development
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,2.984226,Analysis Group\n3.8,"Boston, MA",1981,Consulting
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA",2000,Electrical & Electronic Manufacturing
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY",1998,Advertising & Marketing

## Part 2: String Manipulations (20 Points)

### **Task 2.1 (Location Splitting)**
The `Location` column lists locations as `"City, State"` (e.g., `"Chicago, IL"` or `"Austin, TX"`). Split this column into two separate, brand-new columns: `Job_City` and `Job_State`.

In [21]:
# Write your solution for Task 2.1 here
# Splits only once on the comma
split_locations = jobs['Location'].str.split(',', n=1, expand=True)
jobs['Job_City'] = split_locations[0]
jobs['Job_State'] = split_locations[1]

jobs.head()

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry,Job_City,Job_State
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY",1993,Insurance Carriers,New York,NY
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA",1968,Research & Development,Chantilly,VA
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,2.984226,Analysis Group\n3.8,"Boston, MA",1981,Consulting,Boston,MA
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA",2000,Electrical & Electronic Manufacturing,Newton,MA
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY",1998,Advertising & Marketing,New York,NY

### **Task 2.2 (Whitespace Cleaning)**
The new `Job_State` column might contain accidental leading or trailing empty spaces from the split. Apply a string cleaning function (like `.str.strip()`) to ensure no accidental spaces remain.

In [22]:
# Write your solution for Task 2.2 here
jobs['Job_State'] = jobs['Job_State'].str.strip()
jobs.head()

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry,Job_City,Job_State
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY",1993,Insurance Carriers,New York,NY
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA",1968,Research & Development,Chantilly,VA
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,2.984226,Analysis Group\n3.8,"Boston, MA",1981,Consulting,Boston,MA
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA",2000,Electrical & Electronic Manufacturing,Newton,MA
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY",1998,Advertising & Marketing,New York,NY

## Part 3: Feature Engineering with Grouped Transformations (20 Points)

### **Task 3.1 (Grouped Transform)**
The recruiting team wants to identify jobs that offer a higher-than-average user rating relative to their specific field.

Use `.groupby()` and `.transform()` to calculate the **average (mean) rating for each `Industry`**, broadcasting it back as a new column named `Industry_Avg_Rating`. Then, create a column called `Rating_Above_Industry_Avg` by subtracting `Industry_Avg_Rating` from the job's original `Rating`.

In [23]:
# Write your solution for Task 3.1 here

jobs['Industry_Avg_Rating'] = jobs.groupby('Industry')['Rating'].transform('mean')
jobs['Rating_Above_Industry_Avg'] = jobs['Rating'] - jobs['Industry_Avg_Rating']

jobs[['Industry', 'Rating', 'Industry_Avg_Rating', 'Rating_Above_Industry_Avg']].head()

,Industry,Rating,Industry_Avg_Rating,Rating_Above_Industry_Avg
0,Insurance Carriers,3.100000,3.549599,-0.449599
1,Research & Development,4.200000,3.791778,0.408222
2,Consulting,2.984226,3.635794,-0.651567
3,Electrical & Electronic Manufacturing,3.500000,3.242113,0.257887
4,Advertising & Marketing,2.900000,3.539615,-0.639615

## Part 4: Merging & Aggregating Data (30 Points)

### **Task 4.1 (Dataset Merging)**
You are provided a second, clean reference CSV file named `state_regions.csv` which contains two columns: `State_Abbreviation` and `US_Region` (e.g., *IL, Midwest*).

Perform a **left merge** to add the `US_Region` column to your main job postings dataframe by matching your new `Job_State` column with the reference file's `State_Abbreviation` column.

In [24]:
# Write your solution for Task 4.1 here
jobs = pd.merge(jobs, state_regions, left_on='Job_State', right_on='State_Abbreviation', how='left')

# Verify Results
jobs[['Job_Title', 'Job_State', 'US_Region']].head()

           Job_Title Job_State  US_Region
0  Sr Data Scientist        NY  Northeast
1     Data Scientist        VA      South
2     Data Scientist        MA  Northeast
3     Data Scientist        MA  Northeast
4     Data Scientist        NY  Northeast

### **Task 4.2 (Grouped Aggregation)**
Group your newly merged dataframe by the `US_Region` column. For each region, calculate:
1. The **total count** of job postings in that region.
2. The **average (mean)** employee `Rating` in that region.

In [25]:
# Write your solution for Task 4.2 here
regional_summary = jobs.groupby('US_Region').agg(
    Job_Count=('Job_Title', 'count'),
    Average_Rating=('Rating', 'mean')
).reset_index()

# Display the final summary
display(regional_summary)

   US_Region  Job_Count  Average_Rating
0    Midwest         26        3.348180
1  Northeast         99        3.844553
2      South         85        3.885203
3       West        147        3.738312

### **Task 4.3 (Data Export)**
Save your final, aggregated summary table from Task 4.2 to a new file named `regional_job_summary.csv`.

In [26]:
# Write your solution for Task 4.3 here
regional_summary.to_csv('regional_job_summary.csv', index=False)

print("File 'regional_job_summary.csv' has been successfully saved!")

File 'regional_job_summary.csv' has been successfully saved!